name: total_recall
description: 'A new Flutter project.'
publish_to: 'none'

version: 1.0.0+1

environment:
    sdk: '>=3.2.4 <4.0.0'

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.2
    sherpa_onnx: ^1.10.38
    path_provider: ^2.1.4
    flutter_recorder: ^0.9.4
    path: ^1.9.1
    permission_handler: ^11.3.1
    flutter_background_service: ^5.1.0
    flutter_local_notifications: ^18.0.1
    sqlite3_flutter_libs: 0.5.27
    sqlite3: ^2.7.2

dev_dependencies:
    flutter_lints: ^5.0.0

flutter:
    uses-material-design: true

    assets:
        - assets/sherpa-onnx-streaming-zipformer-en-2023-06-26/encoder-epoch-99-avg-1-chunk-16-left-128.int8.onnx
        - assets/sherpa-onnx-streaming-zipformer-en-2023-06-26/decoder-epoch-99-avg-1-chunk-16-left-128.onnx
        - assets/sherpa-onnx-streaming-zipformer-en-2023-06-26/joiner-epoch-99-avg-1-chunk-16-left-128.onnx
        - assets/sherpa-onnx-streaming-zipformer-en-2023-06-26/tokens.txt
